name: goplayground

kind: pipeline
type: kubernetes

platform:
  os: linux
  arch: arm64

steps:
- name: backend
  image: golang
  environment:
    GOOS: linux
    GOARCH: arm64
  commands:
    - go build
  node_selector:
    kubernetes/arch: arm64

- name: publish
  image: plugins/docker
  settings:
    repo: dkrizic/goplayground
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
