name: goplayground

kind: pipeline
type: kubernetes

steps:
- name: backend
  image: golang
  commands:
    - go build

- name: publish
  image: plugins/docker
  settings:
    repo: dkrizic/goplayground
    tags: [ 1, 1.1, latest ]
    registry: index.docker.io
    auth:
      from_secret: docker_auth

