name: goplayground

kind: pipeline
type: kubernetes

platform:
  os: linux
  arch: arm64

steps:

- name: test
  image: golang:1.10-alpine
  node_selector:
    kubernetes/arch: arm64
  environment:
    GOOS: linux
    GOARCH: arm64
  commands:
    - "go test"

- name: backend
  image: golang
  node_selector:
    kubernetes/arch: arm64
  environment:
    GOOS: linux
    GOARCH: arm64
  commands:
    - "go build"

- name: publish
  image: plugins/docker
  settings:
    repo: dkrizic/goplayground
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
