name: arm64

kind: pipeline
type: kubernetes

platform:
  os: linux
  arch: arm64

node_selector:
  kubernetes.io/arch: arm64

steps:

- name: test
  image: golang
  pull: if-not-exists
  commands:
    - "go test"

- name: build-arm64
  image: golang
  pull: if-not-exists
  environment:
    GOOS: linux
    GOARCH: arm64
  commands:
    - "go build"

- name: publish-arm64
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: dkrizic/goplayground
    tags: [ "${DRONE_COMMIT_SHA:0:7}-linux-arm64" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
name: amd64

kind: pipeline
type: kubernetes

platform:
  os: linux
  arch: amd64

node_selector:
  kubernetes.io/arch: amd64

steps:

- name: build-amd64
  image: golang
  pull: if-not-exists
  environment:
    GOOS: linux
    GOARCH: amd64
  commands:
    - "go build"

- name: publish-amd64
  image: plugins/docker
  pull: if-not-exists
  node_selector:
    kubernetes/arch: amd64
  settings:
    repo: dkrizic/goplayground
    tags: [ "${DRONE_COMMIT_SHA:0:7}-linux-amd64" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
name: manifest

kind: pipeline
type: kubernetes

node_selector:
  kubernetes.io/arch: arm64

steps:

- name: manifest
  image: plugins/manifest
  pull: if-not-exists
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: dkrizic/goplayground:${DRONE_COMMIT_SHA:0:7}
    template: dkrizic/goplayground:${DRONE_COMMIT_SHA:0:7}-OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

depends_on:
  - arm64
  - amd64

---
name: deliver

kind: pipeline
type: kubernetes

node_selector:
  kubernetes.io/arch: arm64

steps:

- name: kubectl
  image: quay.io/honestbee/drone-kubernetes
  kubernetes_server: https://kubernetes.krizic.net:6443
  kubernetes_token:
    from_secret: kube_token
  namespace: goplayground
  deployment: goplayground
  repo: dkrizic/goplayground
  tag: ${DRONE_COMMIT_SHA:0:7}

depends_on:
  - manifest

#- name: deploy
#  image: pelotech/drone-helm3
#  node_selector:
#    kubernetes/arch: amd64
#  settings:
#    mode: upgrade
#    debug: true
#    release: goplayground
#    chart: ./helm/goplayground
#    kube_api_server: https://kubernetes.krizic.net:6443
#    kubernetes_token:
#      from_secret: kube_token
#    namespace: goplayground
#    values_files: helm/home.yaml
#    values:
#    - "image.tag=${DRONE_COMMIT_SHA:0:7}"
#
#
