name: goplayground

kind: pipeline
type: kubernetes

platform:
  os: linux
  arch: arm64

steps:

- name: test
  image: golang
  pull: if-not-exists
  node_selector:
    kubernetes/arch: arm64
  commands:
    - "go test"

- name: build-arm64
  image: golang
  pull: if-not-exists
  node_selector:
    kubernetes/arch: arm64
  environment:
    GOOS: linux
    GOARCH: arm64
  commands:
    - "go build"

- name: publish-arm64
  image: plugins/docker
  pull: if-not-exists
  node_selector:
    kubernetes/arch: arm64
  settings:
    repo: dkrizic/goplayground
    tags: [ "${DRONE_COMMIT_SHA:0:7}-arm64","latest-arm64" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: build-amd64
  image: golang
  pull: if-not-exists
  node_selector:
    kubernetes/arch: arm64
  environment:
    GOOS: linux
    GOARCH: amd64
  commands:
    - "go build"

- name: publish-amd64
  image: plugins/docker
  pull: if-not-exists
  node_selector:
    kubernetes/arch: arm64
  settings:
    repo: dkrizic/goplayground-amd64
    tags: [ "${DRONE_COMMIT_SHA:0:7}-amd64","latest-amd64" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: manifest
  image: plugins/manifest
  pull: if-not-exists
  node_selector:
    kubernetes/arch: arm64
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: dkrizic/goplayground:${DRONE_COMMIT_SHA:0:7}
    template: foo/bar:${DRONE_COMMIT_SHA:0:7}-OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
